services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - postgres-data:/var/lib/postgresql/data

  odoo: 
    image: odoo:19.0
    depends_on:
      - db
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ..:/workspaces/odoo-dev:cached
    command: sleep infinity
    ports:
      - "8069:8069"

volumes:
  postgres-data:
